### ISSUE TITLE
CRITICAL: It is possible to load/unload CarTransport' platform with cars while moving. 

### ISSUE THREAD

**Issue by ArthurAlexandersson** [Chimbobedeh/TDA553-lab1#10]
It's possible to load/unload the cartransport while it's moving. One solution is to override the methods from Vehicle to Truck which increment/decrement the speed and then add an extra condition before calling the super method. E.g. 
`@Override
void startEngine(){
    if(platform.isInValidPosition()){
        super.startEngine()
    }
    else{
        ...
    }
}`

**Comment by rilind404** [comment]
Wouldn't I instead want the condition check in the `loadCar(Car car)` and `unloadCar(Car car)` respectively?

Or did you mean that it is possible to move the cartransporter even if ramp is down?

We realize now that the cartransporter should only be able to move if ramp is raised. Since it can only load cars if ramp is lowered (see my attached sketch of our interpretation of how the ramp should behave).

I have added the condition, corrected code as follows:

```Java
    public void loadCar(Car car) {
        if (isRampActive() //<----- replaced method
            && loadedCars.size() < maximumCapacityOfCars
            && isCarWithinRange(car)
            && this.getCurrentSpeed() == 0.0 // <----- added condition
        ) {
            loadedCars.add(car);
        }
    }

    public void unloadCar(Car car) {
        if (isRampActive() // <----- replaced method
                && loadedCars.size() > 0
                && isLoaded(car)
                && loadedCars.indexOf(car) == loadedCars.size() - 1
                && this.getCurrentSpeed() == 0.0  // <----- added condition
            ) {
            loadedCars.remove(car);
            Position currentPos = getPosition();
            Position newPosition = new Position(
                currentPos.getX(), currentPos.getY() - 1.0
            );
            car.setPosition(newPosition);
        }
    }
```

In addition to this, we had to redefine how we view the ramp states. Cartransporter has a binaryplatform, and is only able to move when ramp is raised. Scania has a progressiveplatform, and is only able to move when ramp is lowered. The "IsRampDown" method was the main issue as we used it as a condition for move with both cartransporter and scania.

Our solution was to replace IsRampDown with IsRampActive. Where we define if it is active in binaryplatform and progressiveplatform respectively (and differently). See the attached sketch again for clarification.

![rampstate](https://user-images.githubusercontent.com/117649966/206192104-aee3897a-a2c3-43ab-b44c-7bdd59bed3ae.png)

Tests have been corrected and they run through with no issues.

**Comment by ArthurAlexandersson** [comment]
Sorry, I were a bit unclear in my comment. 
Checking if the speed is 0 before loading/unloading works. However, it's still possible to call gas/brake/startEngine while the platform is not in it's desired position (up for CarTransport and down for Scania). One posible solution for this is to override these methods in Truck and adding a specific condition before calling the super method.

**Comment by rilind404** [comment]
Added condition to check if ramp is active for overriden gas/brake/startEngine.

```Java
    @Override
    public void gas(double amount) {
        if (!isRampActive()) {
            super.gas(amount);
        }
    }

    @Override
    public void brake(double amount) {
        if (!isRampActive()) {
            super.brake(amount);
        }
    }

    @Override
    public void startEngine() {
        if (!isRampActive()) {
            super.startEngine();
        }
    }
```
