### ISSUE TITLE
lab1# CRITICAL # - TASK 2 

### ISSUE THREAD

**Issue by ArthurAlexandersson** [Chimbobedeh/TDA553-lab1#2]
## CRITICAL ## 
startEngine() should set speed to 0.1, not 1. 
`    public void startEngine() {
	    currentSpeed = 1;
    }`

**Comment by rilind404** [comment]
Fixed, we've encountered issues with our tests failing now. Some have been adjusted in accordance with this change but some still remain due to how our Position class works. I think this was brought up in #3, and we are planning to fix it.

After changes:
` public void startEngine() {currentSpeed = 0.1; }`

Sidenote: Do you want me to close issues when we've fixed them, or are you supposed to close?

**Comment by ArthurAlexandersson** [comment]
Yes, some failed tests are expected since the tests were written to fit the implementation more than the specification.

**Comment by ArthurAlexandersson** [comment]
Leave a comment once an issue has been resolved and I'll close it.
