### ISSUE TITLE
Lab1 # NON-CRITICAL # - Task 4

### ISSUE THREAD

**Issue by ArthurAlexandersson** [Chimbobedeh/TDA553-lab1#4]
## NON-CRITICAL ##
- test methods should preferably only have one assertion test test.
- test classes should preferably test one class each. E.g. Volvo should have its own test class and Saab its own etc.
- speed_does_not_go_below_zero() missing assertion
- the tests on speedFactor() are testing implementation more than specification. It would be better to test these
    through gas and move and check if the position is updated correctly.

**Comment by rilind404** [comment]
We are currently working on lab 2 tasks and will take these notes to consideration when creating new and editing current tests.

**Comment by ArthurAlexandersson** [comment]
Sounds good.

**Comment by rilind404** [comment]
We have now slimmed down the number of tests due to many duplications testing for the same function but in different class (for example turn right test between Saab and Volvo). We have also moved the tests for the common methods in Saab, Volvo, Scania and CarTransport to the superclass Vehicle. 

No tests now contain more than one assertion test.
Created separate test-classes for Volvo, Saab, Scania, CarTransport, Car, Vehicle separately.
`speed_does_not_go_below_zero()` now contains assertion.

`speedFactor()` is no longer tested alone. The method is now tested simultaneously with the tests for turbo and trim as `speedFactor()` is included in the algorithm for calculating new speed after a `gas()` call.
