### ISSUE TITLE
lab1#General#

### ISSUE THREAD

**Issue by ArthurAlexandersson** [Chimbobedeh/TDA553-lab1#5]
## Non-Critical ##
- does speedFactor() have to be public?
- some attributes within car can be made final. E.g. nrDoors.

**Comment by rilind404** [comment]
Following changes have now been made to the code:
`private int nrDoors;` -> `private final int nrDoors;`
`private String modelName;` -> `private final String modelName;`

We thought about making color final, but that is a lot more likely of a car to be changed than the other attributes (realistically speaking).

Regarding `speedFactor()`, the subclasses (Volvo and Saab) have to inherit since `speedFactor()` is abstract. I cannot make it private. We have, however, changed the modifier to `protected` instead. To answer your question, no it doesn't have to be public.
